services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: konga
      POSTGRES_DB: konga
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "konga"]
      interval: 1s
      timeout: 1s
      retries: 3

  migration:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://konga@postgres:5432/konga"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  konga:
    image: pantsel/konga:latest
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_HOST: postgres
      DB_USER: konga
      DB_DATABASE: konga
      NODE_ENV: production
    ports:
      - 0.0.0.0:80:1337
    depends_on:
      postgres:
        condition: service_healthy
